### ISSUE TITLE
Doesn't work in Edge, IE, or Safari due to lack of SharedWorker

### ISSUE THREAD

**Issue by nolanlawson** [Wildhoney/Freelancer#2]
Edge, IE, and Safari don't support SharedWorker right now: http://caniuse.com/#feat=sharedworkers

When you try to load this library in those browsers, you'll see an error because `SharedWorker` is undefined. Here's a repro: http://bl.ocks.org/nolanlawson/raw/28af65df06818b6d4000891714865bc8/

You might want to make SharedWorker optional or look into something like Polymer's [CommonWorker](https://github.com/PolymerElements/app-storage/blob/master/app-indexeddb-mirror/common-worker.html) instead. Or at least document it. 🙂

**Comment by Wildhoney** [comment]
Thanks for this @nolanlawson 👍 I've pushed a small change that should provide a graceful fallback for unsupported workers.

**Comment by Wildhoney** [comment]
[Added to README as well](https://github.com/Wildhoney/Freelancer#unsupported-worker).
